### ISSUE TITLE
Graphviz figures in 4.1 not loading correctly

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/rds-course#109]
In 4.1 we have two figures produced by graphviz. In the online jupyterbook the figures render oversized and cropped:

e.g.
### Figure 1
<img width="827" alt="Screenshot 2021-11-24 at 07 51 30" src="https://user-images.githubusercontent.com/22677759/143197029-e7d7a23f-41ba-48de-9689-3a3ce9c796b8.png">

### Figure 2
<img width="799" alt="Screenshot 2021-11-24 at 07 51 39" src="https://user-images.githubusercontent.com/22677759/143197023-e1e7a15d-97b4-4f30-869e-005a6f973605.png">

Locally, they build like:

<img width="597" alt="Screenshot 2021-11-24 at 07 54 09" src="https://user-images.githubusercontent.com/22677759/143197186-a6f4e3e0-4144-4431-a3ea-139508457a88.png">

<img width="701" alt="Screenshot 2021-11-24 at 07 54 18" src="https://user-images.githubusercontent.com/22677759/143197254-57a4762a-3232-40f6-a4cc-e18f4ff31085.png">

The issue persists in the following cases:

1) the figures as the cell output, with a size attribute being applied through graphviz
2) the figures as saved files, and loaded into the notebook using the image or figure [directives](https://jupyterbook.org/content/figures.html). It seems that resizing doesn't change the ultimate output.
e.g.
````
```{figure} ../../figures/4.1_1.svg
---
height: 150px
name: dataprocess
---

``` 
````

Ideas to try:
- [ ] different file formats (though graphviz doesn't save to certain outputs with a high resolution, e.g. `png`). 
- [ ] raw html instead of myst directives (though this means the nice formatting isn't preserved when the window width changes).

the difficulty with problem solving this issue is that it only crops up on the online version so I've been committing and pushing develop to get the book to build hoping for a quick fix. If we are going to need to delve deeper we might want to temporarily change the book build to a different branch specific for this issue.

It's not a deal breaker for afternoon's teaching (24/11/21), because the instructors can present with their local copies of the book.

**Comment by AoifeHughes** [comment]
Jupyter seems to render this fine for me if you end blocks with a call to the graphviz object rather than asking graphviz to render. (another alternative might be to call ipy Image to display). 

Example of working: [here](https://github.com/alan-turing-institute/rds-course/blob/fix-for-graphviz/coursebook/modules/m4/4.1_What_and_Why.ipynb)
