### ISSUE TITLE
Annual Leave

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/rds-course#12]
Issue to record AL/unavailability for developers of the course.

**Comment by gmingas** [comment]
I will take leave from 16th of August for 3 weeks

**Comment by crangelsmith** [comment]
I'm taking leave on the week of 2nd of July, still not sure exact dates but it will be at least 4 days.

**Comment by jack89roberts** [comment]
Currently, I have planned:

- Week starting 23rd August
- Week starting 6th September

Probably will take at least 1 more week in August/September, maybe 2. And continuing about 1 week/month on average for the rest of the year!
