### ISSUE TITLE
Add Contributors (with all-contributors)

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/rds-course#133]
I've setup [all-contributors](https://allcontributors.org/docs/en/bot/usage) for the repo (I think!)

## Usage

Feel free to add yourself under the categories you think are relevant (see the [emoji key](https://allcontributors.org/docs/en/emoji-key)). 

Post a message below with:

```
@all-contributors please add <user-name> for <categories>
```

### Organisation

- `eventOrganizing`
- `projectManagement`
- `fundingFinding`

### Delivery

- `question` - suggest for course helpers & instructors
- `talk` - suggest for course instructors
- `tutorial` - suggest for helpers and other involvement in hands-on modules

### Developing Material

- `code`
- `content`
- `ideas`

### Reviewing, Fixing, Maintaining

- `bug`
- `review`
- `doc`
- `maintenance`
- `infra`
- `userTesting`

**Comment by jack89roberts** [comment]
@all-contributors please add @jack89roberts for code content ideas question talk

**Comment by jack89roberts** [comment]
@all-contributors please add @jack89roberts for code

**Comment by jack89roberts** [comment]
@all-contributors please add @jack89roberts for code content ideas question talk

**Comment by jack89roberts** [comment]
@all-contributors please add @jack89roberts for code content ideas question talk

**Comment by jack89roberts** [comment]
@alan-turing-institute/rds-course - I've set up all-contributors on the repo, feel free to add yourself under the relevant categories (see top post). It should help @AoifeHughes with preparing the paper author list (https://github.com/alan-turing-institute/rds-course/discussions/127).

**Comment by AoifeHughes** [comment]
https://github.com/all-contributors please add @AoifeHughes for code content ideas question bug review

**Comment by AoifeHughes** [comment]
@all-contributors please add @AoifeHughes for code content ideas question bug review

**Comment by AoifeHughes** [comment]
Thanks for sorting @jack89roberts

**Comment by jack89roberts** [comment]
@all-contributors
please add @callummole for code content ideas question talk bug review infra projectManagement tutorial eventOrganizing research doc maintenance.
please add @crangelsmith for code content ideas question talk bug review projectManagement tutorial eventOrganizing fundingFinding.
please add @jack89roberts for code content ideas question talk bug review infra projectManagement tutorial eventOrganizing research maintenance.
please add @lannelin for code content ideas talk review tutorial fundingFinding question infra.
please add @AoifeHughes for code content ideas question bug review tutorial maintenance.
please add @fedenanni for code content ideas question talk bug review projectManagement tutorial eventOrganizing fundingFinding.
please add @gmingas for code content ideas question talk bug review projectManagement tutorial eventOrganizing fundingFinding.
please add @helendduncan for code content bug review maintenance.
please add @edwardchalstrey1 for code question bug talk tutorial.
please add @ChristinaLast for code tutorial infra content ideas.
please add @radka-j for review bug code.
please add @ots22 for review bug code tutorial question.
please add @triangle-man for tutorial question.
please add @pwochner for tutorial question.
please add @pafoster for review.
please add @nbarlowATI for review question bug talk tutorial.
please add @kasra-hosseini for ideas question review projectManagement tutorial eventOrganizing fundingFinding.
please add @jemrobinson for question talk tutorial projectManagement eventOrganizing.
please add @LouiseABowler for ideas projectManagement fundingFinding.
please add @LydiaFrance for review question bug talk tutorial userTesting.
please add @dsj976 for question tutorial.
please add @KatrionaGoldmann for question tutorial.
please add @craddm for question bug review projectManagement tutorial eventOrganizing.
please add @mhauru for question tutorial.
please add @rchan26 for question tutorial userTesting.
please add @rwood-97 for question tutorial.
please add @mastoffel for question tutorial.
please add @lbokeria for question talk.
please add @dlpbc for question tutorial.
