### ISSUE TITLE
Module 2 (pre-2023 delivery notes)

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/rds-course#143]
Notes from last delivery: #96 (has timings)

Rough plan: Nick starts, switch every break

May not have time to implement these but some thoughts from a look-through.

- [ ] Look at timings from #96 and maybe explicitly mark some sections as optional
- [x] ~~Jazz up section intro pages (e.g. add images), try to reduce walls of text where possible~~
- [x] Check the formatting of bullet points, quotes, code blocks in markdown, numbered lists etc. (in 2.1.1 some seemed to have been borked by line wrapping)
- [ ] Hands-on
   - [x] ~~**Do we still want poetry setup to be part of the hands-on?**~~ (yes, see comment below)
   - [x] link to relevant sections of taught material
   - [x] link a pandas cheat sheet
   - [ ] mark sections by difficulty/as optional/say you don't need to do them all (or in order)
   - [ ] make time to go through solutions together
   - [ ] **Remove solutions from the website?** (or put them somewhere less obvious)
- [x] ~~Could the teaching and hands-on be split across both days?~~
   - likely too late to change this but worth considering in future at least 
   - Day 1: Teach up to and including 2.2.1 Data consistency (this took until ~15:40 in the first delivery), then the first part of the hands-on for the remaining 1hr 15mins or so (may require some re-arranging of exercises to ensure only things that have been taught are needed)
   - Day 2: Rest of teaching material, rest of hands-on

**Comment by craddm** [comment]
A link to the hands-on section for Module 2 has been sent out in the email to participants to help them get set-up beforehand, so the parts about setting up poetry/Python are best left alone at this point. There will be an extra session on Monday morning to help people out if they have issues with it.
