### ISSUE TITLE
Write course advertisement for Turing website

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/rds-course#2]
This should be a short description like [this](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.turingevents.co.uk%2Ftraining%2Fmathematics-of-ml&data=04%7C01%7Cgmingas%40turing.ac.uk%7Cf077543f6ee446825ab708d8fe98e647%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637539280048487226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y7Z6qbL7s1BH6FlU%2Fau6ihhXojoBNUKZM9Wmd3GPN1s%3D&reserved=0) one and Mishka recommended publishing it around September for a second half of November run.

**Comment by kasra-hosseini** [comment]
> There is no specific template other than add relevant sections covering learning outcomes, who delivers the course, the overarching aims, the target audience etc.

**Comment by gmingas** [comment]
Draft found [here](https://hackmd.io/BO9HGrXxTaSYTmQhohziQw). Sent to Mishka for review.
