### ISSUE TITLE
Module 3.3: Directory of visualisations

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/rds-course#22]
## Description

This section is a quick visual overview of the various plots and charts that are commonly used to visualize data and best practices in how to use them.

We will use our data to provide good and bad examples of visualisations and discuss interactively with the students why one is better than the other.

This section is probably the core of this module and should last around 30 to 45m. 

## Outline

- Distributions.
- Proportions.
- Trends.
- Time series.
- Geospatial data.
- Uncertainty.

## References

Material for sections 2 and 3 mainly based on the  [Fundamentals of data visualisation](https://clauswilke.com/dataviz/) book and grammar of Graphics [Wickham's paper](https://byrneslab.net/classes/biol607/readings/wickham_layered-grammar.pdf)

## Estimate time for writing the section

As we will have to build figures with the data this section will take longer. Around 16h.

**Comment by callummole** [comment]
[data viz catalogue](https://datavizcatalogue.com/), linked to through the `Do choose your chart wisely` section in the [eea do's and don'ts](https://www.eea.europa.eu/data-and-maps/daviz/learn-more/chart-dos-and-donts)
