### ISSUE TITLE
Module 3.4 Storytelling with data visualisation.

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/rds-course#23]
# 3.4 Storytelling with data visualisation.

## Description

Discuss ideas and tips in how to make a data viz interesting and fair with the context of the data. We would use our data and create 1 or 2 figures showing the effect of how labels and other aesthetic and labelling decisions can affect how we convey the message (e.g look at figure 6.6 on the [Data Feminism](https://data-feminism.mitpress.mit.edu/pub/czq9dfs5/release/2).

This section should last around 20m.

## Outline

TBD

## Resources

This section can be based on the following resources:
- [Telling a story](https://clauswilke.com/dataviz/telling-a-story.html) section of the Fundamentals for data visualisation.
- [Numbers don't speak for themselves](https://data-feminism.mitpress.mit.edu/pub/czq9dfs5/release/2) chapter of the Data Feminism book.

## Estimated time to write the section

As we will have to build figures with the data this section will take longer. Around 8h.

**Comment by gmingas** [comment]
Chapter 3 of Data Feminism also has some good examples, which along with Chapter 6 can help highlight context, myths about visualisation (e.g. that they are objective or that they should not convey emotion), etc.  Check figures 3.1,  3.2, 3.4 and 3.8.

These elements could be the main EDI content in this module.
