### ISSUE TITLE
Module 4.2: Building a simple model

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/rds-course#34]
# Section 2 - Building a model.

## Description

Take a look at the research question as motivated by M1-3, and build the first simple model.

We will step through selecting your variables and the importance of starting small, breaking up the problem, and only building your model up when you understand the simple one.

- What do we know about our data already (recap on previous). So what variables will be useful? (Discussion on this, probably a big list).
- These are a massive interaction machine. We want to start simple and build up gradually. **feature extraction**
- What are we predicting?
       - self-reported health is an ordered categorical measure
- Introduce **regression** - predicting an outcome as a combination of other variables.
       - most models are regression models of different forms.
       - **briefly** cover the mathematics and necessary assumptions when making a simple regression model.

We will also need to touch on Bayes and Frequentist here.

## How
- As much as possible get to code and visuals quickly. Develop intuition through code and graphing rather than lecturing.

## Estimation
Many of the figures can be adapted from Module 3. It's hard to describe regression concisely yet do it well. 8 hours.

**Comment by crangelsmith** [comment]
Draft https://hackmd.io/rqdHE-OQTbybGCRMs5Ifjg
