### ISSUE TITLE
Module 4.3: Interpreting a model

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/rds-course#35]
# Section 3 - Interpreting a model

## Description

Model interpretation is difficult, and comes with experience. This module will try to distill some key points and offer some advice on how to go about interpreting your model.

- Models only know about the world you build for them.
- Interpretations vary depending on model. For regression models you get coefficients on your inputs. 
- Coefficients are the contribution of that variable to the outcome _assuming you already know all the other variables_. 
    - this is important because the selection of other variables affects your coefficient. You can't interpret coefficients in splendid isolation
    - parameter uncertainty + errors.
    - Brief interlude on probability bayes vs frequentist
- Visualisation helps you understand what the model is telling you. Ask yourself, what does the model think is going on in your data.
    - Explicitly test hypotheses. (can we do inference here? Or do we need uncertainty/residuals from the next section?).
    - prediction/simulation.
- aside: when interpretation goes wrong (case studies).  

## Estimation
Again. Intuitive figures will be key, and there will be a lot of graphing of predictions and different relationships. 8 hours

**Comment by crangelsmith** [comment]
Draft hackmd https://hackmd.io/a0CStccXS3KD6DYPigjDjQ
