### ISSUE TITLE
Define content format and host platform

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/rds-course#6]
We need to decide if the content will be in the same format as the RSE course or if we want to use a different one and potentially some other platform to facilitate DS work.

**Comment by gmingas** [comment]
Notebooks will be used for code initially for prototyping.

We could use the Carpentries platform as it is more polished but could also use the RSE course format.

**Comment by jack89roberts** [comment]
Carpentries template: https://github.com/carpentries/lesson-example

Depending on whether the template counts as software or instructional material it's either MIT licensed or Creative Commons Attribution licensed, either way should be fine for us to use and modify.

**Comment by gmingas** [comment]
Jupyter Books is a good way to present training content as it looks nice and allow to have code that you can run with Binder. We should seriously consider it for the RDS course. Example here: https://alan-turing-institute.github.io/rrp-selfassessment/bias/project-biases.html

**Comment by gmingas** [comment]
A JB template wIll be created, see #17
