### ISSUE TITLE
Course Material Reviewers

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/rds-course#68]
If you'd like to volunteer to review the content of one of the modules please drop us a message here, also indicating whether you have a preference on which module. The modules are:

- [Module 1: Intro to Research Data Science​](https://github.com/alan-turing-institute/rds-course/tree/harmonise/coursebook/modules/m1)
   - Taught: What is RDS, project stages, scoping, EDI, collaboration​
   - Hands-on: Scope a project starting from a dataset and research question, discuss EDI issues​

- [Module 2: Handling data](https://github.com/alan-turing-institute/rds-course/tree/harmonise/coursebook/modules/m2)​
   - Taught: Data sources and types, security, privacy and licensing, loading and manipulating data with Pandas, missing data, common data pre-processing techniques.​
   - Hands-on: Load the dataset into pandas for the first time and perform initial exploration, sanity checks, and cleaning. ​

- [Module 3: Data visualisation and exploration​](https://github.com/alan-turing-institute/rds-course/tree/harmonise/coursebook/modules/m3)
   - Taught: Good practices of data visualisation, storytelling and context, data visualisation for exploration ​
   - Hands-on: Using dataviz to explore and understand the dataset.​

- [Module 4: Modeling​](https://github.com/alan-turing-institute/rds-course/tree/harmonise/coursebook/modules/m4)
   - Taught: General introductory concepts of modeling (probability, generative models, fitting a model), a dive-in logistic regression with a subset from the dataset (UK), model evaluation.​
   - Hands-on: Building a new model on the dataset under different conditions (predictors, ways of treating the data, using a different country), compare it with example from the thought session.

**Note:** Links above are to the current `harmonise` branch, which may not have the latest status of each module.

**Comment by pafoster** [comment]
I'm happy to review either Module 4 or 2.

**Comment by radka-j** [comment]
I'm happy to review. Probably feel most comfortable reviewing 2 or 4 but happy to look at other content if that is useful.

**Comment by nbarlowATI** [comment]
Happy to review, preference would be 2 or 3, but can do whatever is useful.

**Comment by triangle-man** [comment]
I am happy to review any module.

**Comment by gmingas** [comment]
@triangle-man We could use you in Module 1 given others stated preference for other modules. Are you happy with this?

**Comment by triangle-man** [comment]
Sure!
